services:
  glpi-db:
    image: mysql
    container_name: glpi-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    networks:
      - glpi-network
    
  glpi-web:
    image: diouxx/glpi
    container_name: glpi-web
    environment:
      TIMEZONE: America/Sao_Paulo
    networks:
      - glpi-network
    depends_on:
      - glpi-db
    ports:
      - "80:80"
    volumes:
      - "/home/fabio-araujo/Documentos/projects/prometheus-glpi-plugin/prometheus:/var/www/html/glpi/plugins/prometheus"

networks:
  glpi-network:
