# .github/workflows/release-plugin.yml
name: Release GLPI Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Definir versão da release
        id: vars
        run: |
          VERSION=$(date +"%Y.%m.%d-%H%M")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Criar tar.gz da pasta prometheus
        run: |
          tar -czvf prometheus-${{ steps.vars.outputs.version }}.tar.gz prometheus

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          name: "GLPI Plugin Prometheus ${{ steps.vars.outputs.version }}"
          files: prometheus-${{ steps.vars.outputs.version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
